WIP: CHANGELOG-0.10
bookingcom/shipper pull request #371
Opened 2020-10-21 12:06 UTC by hihilla

2020-10-23 12:17 UTC, ArchangelX360 requested changes

2020-10-23 12:17 UTC, ArchangelX360 commented on CHANGELOG-0.10.md
> +### improvements
```suggestion
### Improvements
```

2020-10-23 12:17 UTC, ArchangelX360 commented on CHANGELOG-0.10.md
> +  that means the time that the SSL certificate expires, and a secondly
```suggestion
  that includes the time that the SSL certificate expires, and a secondly
```

2020-10-23 12:17 UTC, ArchangelX360 commented on CHANGELOG-0.10.md
> +  policy][] set to `fail` ([#366][]. This means that the webhook
```suggestion
  policy][] set to `Fail` ([#366][]. This means that the webhook
```

2020-10-27 15:42 UTC, nodo approved these changes
🚢 👍

2020-10-27 15:50 UTC, nodo approved these changes

2020-10-27 15:51 UTC, ArchangelX360 approved these changes

2020-10-27 15:51 UTC, merged